before_script:
  - bash .gitlab-ci.sh
variables:
  MYSQL_DATABASE: tesismanagement
  MYSQL_ROOT_PASSWORD: ppl2018

phpunit:php7.1:mysql5.6:
  image: php:7.1
  services:
    - mysql:5.6
  script:
    - php vendor/bin/phpunit --colors